[phases.setup]
nixPkgs = ['nodejs_22', 'npm-9_x', 'chromium']
nixLibs = ['libnss3', 'libatk1.0-0', 'libatk-bridge2.0-0', 'libcups2', 'libgbm1', 'libasound2t64', 'libpangocairo-1.0-0', 'libxss1', 'libgtk-3-0', 'libxshmfence1']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = []

[start]
cmd = 'npm start'
